# Generated by Django 4.0.4 on 2022-07-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name="Ma'lumot"),
        ),
        migrations.AddField(
            model_name='direction',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name="Ma'lumot"),
        ),
        migrations.AddField(
            model_name='direction',
            name='text_uz',
            field=models.TextField(blank=True, null=True, verbose_name="Ma'lumot"),
        ),
        migrations.AddField(
            model_name='direction',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='direction',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='direction',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
