# Generated by Django 4.0.4 on 2022-07-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_news_text_alter_news_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Yangilik_Yo'nalishi",
                'verbose_name_plural': "Yangiliklar_Yo'nalishlari",
            },
        ),
        migrations.CreateModel(
            name='SubscribeNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.categorynews'),
        ),
    ]
