# Generated by Django 4.0.4 on 2022-07-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_categorynews_subscribenews_news_views_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorynews',
            name='title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='categorynews',
            name='title_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='categorynews',
            name='title_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
