en = {
    'home':"Home",
    'about_us':"About us",
    'services': "Services",
    'news':"News",
    'contact':"Contact",
    'slide_title_1':"Let us take you away",
    'slide_title_2':"Let us take you away",
    'slide_title_3':"Let us take you away",
    'city':"City",
    'departure':"Departure",
    'arrival':"Arrival",
    'budget':'Budget',
    'call_us':"Call us",
    'search': "Search for your trip",
    'search_btn':"search",
    'top_destinations':"Top Destinations",
    'the_best_prices':"The Best Prices",
    'amazing_services':"Amazing Services",
    'footer_title_1':"Subscribe to our newsletter to get the latest trends & news",
    'footer_subtitle_1':"Join our database NOW!",
    'footer_subscribe':"subscribe",
    'footer_title_2':"give us a call",
    'footer_title_3':"come & drop by",
    'footer_title_4':"send us a message",
    'contact_title_1':"Get in touch with us",
    'contact_text_1':"If you have a problem with our site or are dissatisfied with our services, please feel free to contact us. Send us your thoughts using the form below. Every word is important to us!!",
    'address':"address:",
    'phone':"phone:",
    'email':"email:",
    'send':"send",
    'categories':"Categories",
    'latest_news':"Latest News",
    'about_subtitle_1':"simply amazing places",
    'about_title_1':"A few words about us",
    'read_more_btn':"read more",
    'about_title_2':"Why choose us?",
    'fast_services':"Fast Services",
    'great_team':"Great Team",
    'best_deals':"Best Deals",
    'meet_the_team':"Meet The Team",





}